name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          VITE_FIREBASE_API_KEY: "AIzaSyBdCEjsO9PXZ-bPLKwU2wL84cNw5bjYAlc"
          VITE_FIREBASE_AUTH_DOMAIN: "church-manager-e3124.firebaseapp.com"
          VITE_FIREBASE_PROJECT_ID: "church-manager-e3124"
          VITE_FIREBASE_STORAGE_BUCKET: "church-manager-e3124.firebasestorage.app"
          VITE_FIREBASE_MESSAGING_SENDER_ID: "39535536696"
          VITE_FIREBASE_APP_ID: "1:39535536696:web:bfe767ba56fcf3d71914cd"
          VITE_FIREBASE_MEASUREMENT_ID: "G-P5J7MZF9VQ"

      - name: Create 404 page for SPA routing
        run: cp dist/index.html dist/404.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
